:document:
  :source: 'document.glyph'
  :author: ""
  :title: ""
  :filename: ""
  :output: ""
  :output_targets: [:html, :pdf]
:structure:
  :headers: [:section, :chapter, :part, :introduction, :contents, :preface, :appendix, :foreword, :afterword, :glossary, :index]  
  :first_header_level: 2
:pdf_renderer: 'prince'
:filters:
  :by_file_extension: true
  :target: 'html'
  :redcloth:
    :restrictions: []
