:document:
  :source: 'document.glyph'
  :author: ""
  :title: ""
  :subtitle: ""
  :filename: ""
  :revision: "rev. 1"
  :draft: false
  :output: 'html'
:language:
  :set: 'glyph' # xml, core, filters
  :options:
    :xml_fallback: true
:tools:
  :pdf_generator: 'prince'
:filters:
  :by_file_extension: true
  :highlighter: 'coderay'
  :target: 'html'
  :markdown:
    :converter: 'bluecloth'
  :redcloth:
    :restrictions: []
  :coderay:
    # See options at http://coderay.rubychan.de/doc/classes/CodeRay/Encoders/HTML.html
    :css: :class 
  :ultraviolet:
    :line_numbers: false
    :theme: 'blackboard'
:system:
  :quiet: false
  :output_targets: [:html, :pdf]
  :structure:
    :hidden:
      - :imprint
      - :dedication
      - :inspiration
      - :postscript
      - :colophon
      - :promotion
    :special:
      - :foreword
      - :acknowledgement
      - :prologue
      - :epilogue
      - :addendum
      - :glossary
      - :bibliography
      - :references
      - :index
      - :lot
      - :lof
    :frontmatter:
      - :preface
      - :imprint
      - :dedication
      - :inspiration
      - :foreword
      - :introduction
      - :acknowledgement
      - :prologue
    :bodymatter:
      - :volume
      - :part
      - :chapter
    :backmatter:
      - :epilogue
      - :afterword
      - :postscript
      - :appendix
      - :addendum
      - :glossary
      - :colophon
      - :bibliography
      - :promotion
      - :references
      - :index
      - :lot
      - :lof
