--- 
:highlighters: 
  :current: ultraviolet
  :ultraviolet: 
    :theme: blackboard
:document: 
  :output: html
  :title: Glyph
  :subtitle: Rapid Document Authoring Framework
  :author: Fabio Cevasco
  :filename: glyph
