--- 
:structure: 
  :headers: 
  - :section
  - :preface
  - :foreword
  - :introduction
  - :acknowledgement
  - :prologue
  - :epilogue
  - :afterword
  - :appendix
  - :addendum
  - :glossary
  - :bibliography
  - :references
  - :index
  - :lot
  - :lof
  - :volume
  - :book
  - :part
  - :chapter
:document: 
  :subtitle: Rapid Document Authoring Framework
  :output: html
  :filename: glyph
  :author: Fabio Cevasco
  :title: Glyph
