--- 
:document: 
  :output: html
  :title: Glyph
  :subtitle: Rapid Document Authoring Framework
  :author: Fabio Cevasco
  :revision: "v0.3.0"
  :filename: glyph
  :draft: true
:filters:
  :highlighter: ultraviolet
